analytics: {}
color:
  brandColors:
    - '#ffffff'
    - '#523014'
    - '#b5cef6'
    - '#9f8971'
    - '#7c5e3a'
  brandStrength: 0
  lightness: 0.022522
  rhythmicContrast: 0.014639
  saturation: 0.009009
cta: {}
layout_spectrum: 0.25202584243379533
name: Vera Chicago
opengraph: {}
purpose: []
typography_spectrum: 0.14560143114067614
