name: Vera Chicago
favicon: null
layout_spectrum: 0.25202584243379533
typography_spectrum: 0.14560143114067614
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.6074784921947867
  lightness: 0.29698543762788177
  saturation: 0.9180256349500269
  rhythmicContrast: 0.9622346926480532
purpose: []
