analytics: {}
color:
  brandColors:
    - '#ffffff'
    - '#523014'
    - '#b5cef6'
    - '#9f8971'
    - '#7c5e3a'
  brandStrength: 0.6875
  lightness: 0.375
  rhythmicContrast: 0
  saturation: 0.6875
cta: {}
layout_spectrum: 0.808558
name: Vera Chicago
opengraph: {}
purpose: []
typography_spectrum: 0.14560143114067614
