name: Vera Chicago
favicon: null
layout_spectrum: 0
typography_spectrum: 0.14560143114067614
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#523014'
    - '#b5cef6'
    - '#9f8971'
    - '#7c5e3a'
  brandStrength: 0
  lightness: 0.375
  saturation: 0.6875
  rhythmicContrast: 0
purpose: []
